using System.Text;

public static class LongHtmlStringBuilderSample
{
    public static string BuildHtml()
    {
        var sb = new StringBuilder();

        // ----------------------------
        // HTML header
        // ----------------------------
        sb.AppendLine("<!doctype html>");
        sb.AppendLine("<html lang=\"ja\">");
        sb.AppendLine("<head>");
        sb.AppendLine("  <meta charset=\"utf-8\" />");
        sb.AppendLine("  <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />");
        sb.AppendLine("  <title>Mini Inventory Manager</title>");
        sb.AppendLine("");
        sb.AppendLine("  <style>");
        sb.AppendLine("    :root {");
        sb.AppendLine("      --bg: #0f172a;");
        sb.AppendLine("      --panel: #111827;");
        sb.AppendLine("      --text: #e5e7eb;");
        sb.AppendLine("      --muted: #9ca3af;");
        sb.AppendLine("      --accent: #60a5fa;");
        sb.AppendLine("      --danger: #f87171;");
        sb.AppendLine("      --ok: #34d399;");
        sb.AppendLine("      --border: rgba(255,255,255,0.12);");
        sb.AppendLine("      --shadow: 0 10px 25px rgba(0,0,0,0.35);");
        sb.AppendLine("      --radius: 14px;");
        sb.AppendLine("      --mono: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, \"Liberation Mono\", \"Courier New\", monospace;");
        sb.AppendLine("      --sans: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial, \"Apple Color Emoji\", \"Segoe UI Emoji\";");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    * { box-sizing: border-box; }");
        sb.AppendLine("");
        sb.AppendLine("    body {");
        sb.AppendLine("      margin: 0;");
        sb.AppendLine("      background: linear-gradient(160deg, #0b1023, #0f172a 60%, #0b1023);");
        sb.AppendLine("      color: var(--text);");
        sb.AppendLine("      font-family: var(--sans);");
        sb.AppendLine("      line-height: 1.45;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    header {");
        sb.AppendLine("      position: sticky;");
        sb.AppendLine("      top: 0;");
        sb.AppendLine("      z-index: 10;");
        sb.AppendLine("      backdrop-filter: blur(10px);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.65);");
        sb.AppendLine("      border-bottom: 1px solid var(--border);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .wrap {");
        sb.AppendLine("      max-width: 1100px;");
        sb.AppendLine("      margin: 0 auto;");
        sb.AppendLine("      padding: 18px 18px 40px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .row {");
        sb.AppendLine("      display: grid;");
        sb.AppendLine("      grid-template-columns: 1fr;");
        sb.AppendLine("      gap: 16px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    @media (min-width: 900px) {");
        sb.AppendLine("      .row {");
        sb.AppendLine("        grid-template-columns: 420px 1fr;");
        sb.AppendLine("        align-items: start;");
        sb.AppendLine("      }");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .title {");
        sb.AppendLine("      display: flex;");
        sb.AppendLine("      align-items: center;");
        sb.AppendLine("      gap: 12px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .logo {");
        sb.AppendLine("      width: 36px;");
        sb.AppendLine("      height: 36px;");
        sb.AppendLine("      border-radius: 10px;");
        sb.AppendLine("      background: radial-gradient(circle at 30% 30%, #60a5fa, #2563eb 55%, #1e3a8a);");
        sb.AppendLine("      box-shadow: var(--shadow);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    h1 {");
        sb.AppendLine("      margin: 0;");
        sb.AppendLine("      font-size: 18px;");
        sb.AppendLine("      letter-spacing: 0.2px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .subtitle {");
        sb.AppendLine("      margin: 2px 0 0;");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .panel {");
        sb.AppendLine("      background: rgba(17, 24, 39, 0.75);");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      border-radius: var(--radius);");
        sb.AppendLine("      box-shadow: var(--shadow);");
        sb.AppendLine("      overflow: hidden;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .panelHeader {");
        sb.AppendLine("      padding: 14px 14px;");
        sb.AppendLine("      border-bottom: 1px solid var(--border);");
        sb.AppendLine("      display: flex;");
        sb.AppendLine("      align-items: center;");
        sb.AppendLine("      justify-content: space-between;");
        sb.AppendLine("      gap: 10px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .panelHeader .hint {");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .panelBody {");
        sb.AppendLine("      padding: 14px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    label {");
        sb.AppendLine("      display: block;");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("      margin-bottom: 6px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    input, select, textarea {");
        sb.AppendLine("      width: 100%;");
        sb.AppendLine("      padding: 10px 12px;");
        sb.AppendLine("      border-radius: 12px;");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.65);");
        sb.AppendLine("      color: var(--text);");
        sb.AppendLine("      outline: none;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    input:focus, select:focus, textarea:focus {");
        sb.AppendLine("      border-color: rgba(96, 165, 250, 0.55);");
        sb.AppendLine("      box-shadow: 0 0 0 4px rgba(96, 165, 250, 0.15);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .grid2 {");
        sb.AppendLine("      display: grid;");
        sb.AppendLine("      grid-template-columns: 1fr 1fr;");
        sb.AppendLine("      gap: 12px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .grid3 {");
        sb.AppendLine("      display: grid;");
        sb.AppendLine("      grid-template-columns: 1fr 1fr 1fr;");
        sb.AppendLine("      gap: 12px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .actions {");
        sb.AppendLine("      display: flex;");
        sb.AppendLine("      gap: 10px;");
        sb.AppendLine("      flex-wrap: wrap;");
        sb.AppendLine("      margin-top: 10px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    button {");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.7);");
        sb.AppendLine("      color: var(--text);");
        sb.AppendLine("      padding: 9px 12px;");
        sb.AppendLine("      border-radius: 12px;");
        sb.AppendLine("      cursor: pointer;");
        sb.AppendLine("      transition: transform 0.05s ease, background 0.15s ease, border-color 0.15s ease;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    button:hover {");
        sb.AppendLine("      border-color: rgba(96, 165, 250, 0.55);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.9);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    button:active {");
        sb.AppendLine("      transform: translateY(1px);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .primary {");
        sb.AppendLine("      border-color: rgba(96, 165, 250, 0.55);");
        sb.AppendLine("      background: rgba(37, 99, 235, 0.22);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .danger {");
        sb.AppendLine("      border-color: rgba(248, 113, 113, 0.55);");
        sb.AppendLine("      background: rgba(248, 113, 113, 0.12);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .ghost {");
        sb.AppendLine("      border-color: transparent;");
        sb.AppendLine("      background: transparent;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .note {");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("      margin-top: 10px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .error {");
        sb.AppendLine("      color: var(--danger);");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      margin-top: 6px;");
        sb.AppendLine("      min-height: 16px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .success {");
        sb.AppendLine("      color: var(--ok);");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      margin-top: 6px;");
        sb.AppendLine("      min-height: 16px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .toolbar {");
        sb.AppendLine("      display: flex;");
        sb.AppendLine("      gap: 10px;");
        sb.AppendLine("      flex-wrap: wrap;");
        sb.AppendLine("      align-items: center;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .pill {");
        sb.AppendLine("      font-family: var(--mono);");
        sb.AppendLine("      font-size: 11px;");
        sb.AppendLine("      padding: 6px 10px;");
        sb.AppendLine("      border-radius: 999px;");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.55);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    table {");
        sb.AppendLine("      width: 100%;");
        sb.AppendLine("      border-collapse: collapse;");
        sb.AppendLine("      overflow: hidden;");
        sb.AppendLine("      border-radius: 12px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    thead th {");
        sb.AppendLine("      text-align: left;");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("      padding: 10px;");
        sb.AppendLine("      border-bottom: 1px solid var(--border);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.5);");
        sb.AppendLine("      position: sticky;");
        sb.AppendLine("      top: 64px;"); // headerの高さ（概算）
        sb.AppendLine("      z-index: 5;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    tbody td {");
        sb.AppendLine("      padding: 10px;");
        sb.AppendLine("      border-bottom: 1px solid var(--border);");
        sb.AppendLine("      vertical-align: top;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    tbody tr:hover {");
        sb.AppendLine("      background: rgba(96, 165, 250, 0.08);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .tag {");
        sb.AppendLine("      display: inline-flex;");
        sb.AppendLine("      align-items: center;");
        sb.AppendLine("      gap: 6px;");
        sb.AppendLine("      padding: 3px 8px;");
        sb.AppendLine("      border-radius: 999px;");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.55);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .dot {");
        sb.AppendLine("      width: 8px;");
        sb.AppendLine("      height: 8px;");
        sb.AppendLine("      border-radius: 50%;");
        sb.AppendLine("      background: var(--muted);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .dot.ok { background: var(--ok); }");
        sb.AppendLine("    .dot.low { background: #fbbf24; }");
        sb.AppendLine("    .dot.out { background: var(--danger); }");
        sb.AppendLine("");
        sb.AppendLine("    .small {");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .kpi {");
        sb.AppendLine("      display: grid;");
        sb.AppendLine("      grid-template-columns: 1fr 1fr 1fr;");
        sb.AppendLine("      gap: 10px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .kpi .card {");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      border-radius: 12px;");
        sb.AppendLine("      padding: 10px;");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.5);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .kpi .label {");
        sb.AppendLine("      font-size: 11px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .kpi .value {");
        sb.AppendLine("      font-size: 18px;");
        sb.AppendLine("      margin-top: 2px;");
        sb.AppendLine("      font-family: var(--mono);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .modalBack {");
        sb.AppendLine("      position: fixed;");
        sb.AppendLine("      inset: 0;");
        sb.AppendLine("      background: rgba(0,0,0,0.6);");
        sb.AppendLine("      display: none;");
        sb.AppendLine("      align-items: center;");
        sb.AppendLine("      justify-content: center;");
        sb.AppendLine("      padding: 18px;");
        sb.AppendLine("      z-index: 999;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .modal {");
        sb.AppendLine("      width: min(680px, 100%);");
        sb.AppendLine("      border-radius: var(--radius);");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      background: rgba(17, 24, 39, 0.95);");
        sb.AppendLine("      box-shadow: var(--shadow);");
        sb.AppendLine("      overflow: hidden;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .modalHeader {");
        sb.AppendLine("      padding: 14px;");
        sb.AppendLine("      border-bottom: 1px solid var(--border);");
        sb.AppendLine("      display: flex;");
        sb.AppendLine("      align-items: center;");
        sb.AppendLine("      justify-content: space-between;");
        sb.AppendLine("      gap: 10px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .modalTitle {");
        sb.AppendLine("      margin: 0;");
        sb.AppendLine("      font-size: 14px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .modalBody {");
        sb.AppendLine("      padding: 14px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .code {");
        sb.AppendLine("      font-family: var(--mono);");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("      padding: 12px;");
        sb.AppendLine("      border-radius: 12px;");
        sb.AppendLine("      border: 1px solid var(--border);");
        sb.AppendLine("      background: rgba(15, 23, 42, 0.65);");
        sb.AppendLine("      white-space: pre;");
        sb.AppendLine("      overflow: auto;");
        sb.AppendLine("      max-height: 320px;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    .footerHint {");
        sb.AppendLine("      margin-top: 10px;");
        sb.AppendLine("      color: var(--muted);");
        sb.AppendLine("      font-size: 12px;");
        sb.AppendLine("    }");
        sb.AppendLine("  </style>");
        sb.AppendLine("</head>");
        sb.AppendLine("");
        sb.AppendLine("<body>");
        sb.AppendLine("  <header>");
        sb.AppendLine("    <div class=\"wrap\">");
        sb.AppendLine("      <div class=\"title\">");
        sb.AppendLine("        <div class=\"logo\" aria-hidden=\"true\"></div>");
        sb.AppendLine("        <div>");
        sb.AppendLine("          <h1>Mini Inventory Manager</h1>");
        sb.AppendLine("          <div class=\"subtitle\">ローカルで動く / 保存は LocalStorage / JSだけで完結</div>");
        sb.AppendLine("        </div>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </header>");
        sb.AppendLine("");
        sb.AppendLine("  <main class=\"wrap\">");
        sb.AppendLine("    <div class=\"row\">");
        sb.AppendLine("      <section class=\"panel\" aria-label=\"入力フォーム\">");
        sb.AppendLine("        <div class=\"panelHeader\">");
        sb.AppendLine("          <div>");
        sb.AppendLine("            <div style=\"font-weight:600;\">Item追加</div>");
        sb.AppendLine("            <div class=\"hint\">必須: 名前 / 数量 / カテゴリ</div>");
        sb.AppendLine("          </div>");
        sb.AppendLine("          <button class=\"ghost\" id=\"btnOpenHelp\" type=\"button\">Help</button>");
        sb.AppendLine("        </div>");
        sb.AppendLine("");
        sb.AppendLine("        <div class=\"panelBody\">");
        sb.AppendLine("          <form id=\"form\">");
        sb.AppendLine("            <div style=\"margin-bottom:12px;\">");
        sb.AppendLine("              <label for=\"name\">名前 *</label>");
        sb.AppendLine("              <input id=\"name\" name=\"name\" autocomplete=\"off\" placeholder=\"例: USB-C Cable\" />");
        sb.AppendLine("              <div class=\"error\" id=\"errName\"></div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("");
        sb.AppendLine("            <div class=\"grid2\" style=\"margin-bottom:12px;\">");
        sb.AppendLine("              <div>");
        sb.AppendLine("                <label for=\"qty\">数量 *</label>");
        sb.AppendLine("                <input id=\"qty\" name=\"qty\" inputmode=\"numeric\" placeholder=\"例: 3\" />");
        sb.AppendLine("                <div class=\"error\" id=\"errQty\"></div>");
        sb.AppendLine("              </div>");
        sb.AppendLine("              <div>");
        sb.AppendLine("                <label for=\"category\">カテゴリ *</label>");
        sb.AppendLine("                <select id=\"category\" name=\"category\">");
        sb.AppendLine("                  <option value=\"\">選択してください</option>");
        sb.AppendLine("                  <option value=\"cable\">Cable</option>");
        sb.AppendLine("                  <option value=\"adapter\">Adapter</option>");
        sb.AppendLine("                  <option value=\"tool\">Tool</option>");
        sb.AppendLine("                  <option value=\"other\">Other</option>");
        sb.AppendLine("                </select>");
        sb.AppendLine("                <div class=\"error\" id=\"errCategory\"></div>");
        sb.AppendLine("              </div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("");
        sb.AppendLine("            <div class=\"grid3\" style=\"margin-bottom:12px;\">");
        sb.AppendLine("              <div>");
        sb.AppendLine("                <label for=\"price\">価格</label>");
        sb.AppendLine("                <input id=\"price\" name=\"price\" inputmode=\"decimal\" placeholder=\"例: 1200\" />");
        sb.AppendLine("              </div>");
        sb.AppendLine("              <div>");
        sb.AppendLine("                <label for=\"min\">最小在庫</label>");
        sb.AppendLine("                <input id=\"min\" name=\"min\" inputmode=\"numeric\" placeholder=\"例: 2\" />");
        sb.AppendLine("              </div>");
        sb.AppendLine("              <div>");
        sb.AppendLine("                <label for=\"status\">ステータス</label>");
        sb.AppendLine("                <select id=\"status\" name=\"status\">");
        sb.AppendLine("                  <option value=\"active\">active</option>");
        sb.AppendLine("                  <option value=\"hold\">hold</option>");
        sb.AppendLine("                  <option value=\"archived\">archived</option>");
        sb.AppendLine("                </select>");
        sb.AppendLine("              </div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("");
        sb.AppendLine("            <div style=\"margin-bottom:12px;\">");
        sb.AppendLine("              <label for=\"memo\">メモ</label>");
        sb.AppendLine("              <textarea id=\"memo\" name=\"memo\" rows=\"3\" placeholder=\"任意: 例) 発注先や注意点\"></textarea>");
        sb.AppendLine("            </div>");
        sb.AppendLine("");
        sb.AppendLine("            <div class=\"actions\">");
        sb.AppendLine("              <button class=\"primary\" id=\"btnAdd\" type=\"submit\">追加</button>");
        sb.AppendLine("              <button id=\"btnReset\" type=\"button\">入力クリア</button>");
        sb.AppendLine("              <button class=\"danger\" id=\"btnClearAll\" type=\"button\">全削除</button>");
        sb.AppendLine("            </div>");
        sb.AppendLine("");
        sb.AppendLine("            <div class=\"success\" id=\"okMsg\"></div>");
        sb.AppendLine("            <div class=\"note\">");
        sb.AppendLine("              ※保存先はブラウザの LocalStorage。別PC/別ブラウザには同期されない。");
        sb.AppendLine("            </div>");
        sb.AppendLine("          </form>");
        sb.AppendLine("        </div>");
        sb.AppendLine("      </section>");
        sb.AppendLine("");
        sb.AppendLine("      <section class=\"panel\" aria-label=\"一覧\">");
        sb.AppendLine("        <div class=\"panelHeader\">");
        sb.AppendLine("          <div style=\"display:flex;flex-direction:column;gap:4px;\">");
        sb.AppendLine("            <div style=\"font-weight:600;\">一覧</div>");
        sb.AppendLine("            <div class=\"hint\">検索/フィルタ/ソート/エクスポート</div>");
        sb.AppendLine("          </div>");
        sb.AppendLine("");
        sb.AppendLine("          <div class=\"toolbar\">");
        sb.AppendLine("            <input id=\"search\" placeholder=\"検索: 名前/カテゴリ/メモ\" style=\"width:220px;\" />");
        sb.AppendLine("            <select id=\"filterStatus\" style=\"width:140px;\">");
        sb.AppendLine("              <option value=\"\">status: all</option>");
        sb.AppendLine("              <option value=\"active\">active</option>");
        sb.AppendLine("              <option value=\"hold\">hold</option>");
        sb.AppendLine("              <option value=\"archived\">archived</option>");
        sb.AppendLine("            </select>");
        sb.AppendLine("            <button id=\"btnExport\" type=\"button\">Export</button>");
        sb.AppendLine("          </div>");
        sb.AppendLine("        </div>");
        sb.AppendLine("");
        sb.AppendLine("        <div class=\"panelBody\">");
        sb.AppendLine("          <div class=\"kpi\" style=\"margin-bottom:12px;\">");
        sb.AppendLine("            <div class=\"card\">");
        sb.AppendLine("              <div class=\"label\">items</div>");
        sb.AppendLine("              <div class=\"value\" id=\"kpiItems\">0</div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("            <div class=\"card\">");
        sb.AppendLine("              <div class=\"label\">low stock</div>");
        sb.AppendLine("              <div class=\"value\" id=\"kpiLow\">0</div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("            <div class=\"card\">");
        sb.AppendLine("              <div class=\"label\">total qty</div>");
        sb.AppendLine("              <div class=\"value\" id=\"kpiQty\">0</div>");
        sb.AppendLine("            </div>");
        sb.AppendLine("          </div>");
        sb.AppendLine("");
        sb.AppendLine("          <div style=\"display:flex;gap:10px;flex-wrap:wrap;margin-bottom:10px;\">");
        sb.AppendLine("            <span class=\"pill\" id=\"pillSort\">sort: created desc</span>");
        sb.AppendLine("            <button id=\"btnSort\" type=\"button\">Sort切替</button>");
        sb.AppendLine("            <button id=\"btnSeed\" type=\"button\">サンプル投入</button>");
        sb.AppendLine("          </div>");
        sb.AppendLine("");
        sb.AppendLine("          <div style=\"overflow:auto;max-height:520px;border-radius:12px;border:1px solid var(--border);\">");
        sb.AppendLine("            <table aria-label=\"items table\">");
        sb.AppendLine("              <thead>");
        sb.AppendLine("                <tr>");
        sb.AppendLine("                  <th style=\"min-width:240px;\">Name</th>");
        sb.AppendLine("                  <th style=\"min-width:120px;\">Category</th>");
        sb.AppendLine("                  <th style=\"min-width:110px;\">Qty</th>");
        sb.AppendLine("                  <th style=\"min-width:120px;\">Status</th>");
        sb.AppendLine("                  <th style=\"min-width:110px;\">Price</th>");
        sb.AppendLine("                  <th style=\"min-width:220px;\">Memo</th>");
        sb.AppendLine("                  <th style=\"min-width:140px;\">Actions</th>");
        sb.AppendLine("                </tr>");
        sb.AppendLine("              </thead>");
        sb.AppendLine("              <tbody id=\"tbody\">");
        sb.AppendLine("                <!-- JSが描画 -->");
        sb.AppendLine("              </tbody>");
        sb.AppendLine("            </table>");
        sb.AppendLine("          </div>");
        sb.AppendLine("");
        sb.AppendLine("          <div class=\"footerHint\">");
        sb.AppendLine("            ヒント: Qtyが「最小在庫」より小さいと low 表示。0なら out 表示。");
        sb.AppendLine("          </div>");
        sb.AppendLine("        </div>");
        sb.AppendLine("      </section>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </main>");
        sb.AppendLine("");
        sb.AppendLine("  <div class=\"modalBack\" id=\"modalBack\" aria-hidden=\"true\">");
        sb.AppendLine("    <div class=\"modal\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"modalTitle\">");
        sb.AppendLine("      <div class=\"modalHeader\">");
        sb.AppendLine("        <h2 class=\"modalTitle\" id=\"modalTitle\">Help / Export Preview</h2>");
        sb.AppendLine("        <button class=\"ghost\" id=\"btnCloseModal\" type=\"button\">Close</button>");
        sb.AppendLine("      </div>");
        sb.AppendLine("      <div class=\"modalBody\">");
        sb.AppendLine("        <div class=\"small\">");
        sb.AppendLine("          ・追加したデータは LocalStorage に保存されます。<br />");
        sb.AppendLine("          ・Export は現在表示中（検索/フィルタ適用後）のデータを JSON で表示します。<br />");
        sb.AppendLine("          ・Delete は即削除、Archive はステータス変更のみです。");
        sb.AppendLine("        </div>");
        sb.AppendLine("        <div style=\"height:10px;\"></div>");
        sb.AppendLine("        <div class=\"code\" id=\"exportBox\">{}</div>");
        sb.AppendLine("      </div>");
        sb.AppendLine("    </div>");
        sb.AppendLine("  </div>");
        sb.AppendLine("");
        sb.AppendLine("  <script>");

        // ----------------------------
        // JS（C#文字列内なので \" や \\ が必要）
        // ----------------------------
        sb.AppendLine("    const $ = (selector) => document.querySelector(selector);");
        sb.AppendLine("    const STORAGE_KEY = \"mini_inventory_items_v1\";");
        sb.AppendLine("");
        sb.AppendLine("    function nowIso() {");
        sb.AppendLine("      return new Date().toISOString();");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function safeParseInt(value, fallback = 0) {");
        sb.AppendLine("      const n = parseInt(value, 10);");
        sb.AppendLine("      return Number.isFinite(n) ? n : fallback;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function safeParseFloat(value, fallback = 0) {");
        sb.AppendLine("      const n = parseFloat(value);");
        sb.AppendLine("      return Number.isFinite(n) ? n : fallback;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function escapeHtml(text) {");
        sb.AppendLine("      return String(text)");
        sb.AppendLine("        .replaceAll(\"&\", \"&amp;\")");
        sb.AppendLine("        .replaceAll(\"<\", \"&lt;\")");
        sb.AppendLine("        .replaceAll(\">\", \"&gt;\")");
        sb.AppendLine("        .replaceAll(\"\\\"\", \"&quot;\")");
        sb.AppendLine("        .replaceAll(\"'\", \"&#39;\");");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function toCategoryLabel(cat) {");
        sb.AppendLine("      switch (cat) {");
        sb.AppendLine("        case \"cable\": return \"Cable\";");
        sb.AppendLine("        case \"adapter\": return \"Adapter\";");
        sb.AppendLine("        case \"tool\": return \"Tool\";");
        sb.AppendLine("        case \"other\": return \"Other\";");
        sb.AppendLine("        default: return \"(unknown)\";");
        sb.AppendLine("      }");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function stockLevelDot(qty, min) {");
        sb.AppendLine("      if (qty <= 0) return \"out\";");
        sb.AppendLine("      if (qty < min) return \"low\";");
        sb.AppendLine("      return \"ok\";");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    const state = {");
        sb.AppendLine("      items: [],");
        sb.AppendLine("      sortMode: \"created_desc\",");
        sb.AppendLine("      search: \"\",");
        sb.AppendLine("      filterStatus: \"\",");
        sb.AppendLine("    };");
        sb.AppendLine("");
        sb.AppendLine("    function loadItems() {");
        sb.AppendLine("      try {");
        sb.AppendLine("        const raw = localStorage.getItem(STORAGE_KEY);");
        sb.AppendLine("        if (!raw) return [];");
        sb.AppendLine("        const parsed = JSON.parse(raw);");
        sb.AppendLine("        if (!Array.isArray(parsed)) return [];");
        sb.AppendLine("        return parsed;");
        sb.AppendLine("      } catch {");
        sb.AppendLine("        return [];");
        sb.AppendLine("      }");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function saveItems(items) {");
        sb.AppendLine("      localStorage.setItem(STORAGE_KEY, JSON.stringify(items));");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function validate(formData) {");
        sb.AppendLine("      const errors = {};");
        sb.AppendLine("");
        sb.AppendLine("      const name = (formData.name || \"\").trim();");
        sb.AppendLine("      const qty = safeParseInt(formData.qty, NaN);");
        sb.AppendLine("      const category = (formData.category || \"\").trim();");
        sb.AppendLine("");
        sb.AppendLine("      if (!name) {");
        sb.AppendLine("        errors.name = \"名前は必須です\";");
        sb.AppendLine("      } else if (name.length > 50) {");
        sb.AppendLine("        errors.name = \"名前は50文字以内にしてね\";");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      if (!Number.isFinite(qty)) {");
        sb.AppendLine("        errors.qty = \"数量は数字で入力してね\";");
        sb.AppendLine("      } else if (qty < 0 || qty > 9999) {");
        sb.AppendLine("        errors.qty = \"数量は 0〜9999 の範囲にしてね\";");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      if (!category) {");
        sb.AppendLine("        errors.category = \"カテゴリは必須です\";");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      return errors;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function setErrors(errors) {");
        sb.AppendLine("      $(\"#errName\").textContent = errors.name || \"\";");
        sb.AppendLine("      $(\"#errQty\").textContent = errors.qty || \"\";");
        sb.AppendLine("      $(\"#errCategory\").textContent = errors.category || \"\";");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function setOk(text) {");
        sb.AppendLine("      $(\"#okMsg\").textContent = text || \"\";");
        sb.AppendLine("      if (text) {");
        sb.AppendLine("        setTimeout(() => { $(\"#okMsg\").textContent = \"\"; }, 1300);");
        sb.AppendLine("      }");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function getVisibleItems() {");
        sb.AppendLine("      const q = state.search.trim().toLowerCase();");
        sb.AppendLine("      const st = state.filterStatus;");
        sb.AppendLine("");
        sb.AppendLine("      let list = state.items.slice();");
        sb.AppendLine("");
        sb.AppendLine("      if (st) {");
        sb.AppendLine("        list = list.filter(x => x.status === st);");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      if (q) {");
        sb.AppendLine("        list = list.filter(x => {");
        sb.AppendLine("          const blob = `${x.name} ${x.category} ${x.memo}`.toLowerCase();");
        sb.AppendLine("          return blob.includes(q);");
        sb.AppendLine("        });");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      switch (state.sortMode) {");
        sb.AppendLine("        case \"created_asc\":");
        sb.AppendLine("          list.sort((a, b) => a.createdAt.localeCompare(b.createdAt));");
        sb.AppendLine("          break;");
        sb.AppendLine("        case \"name_asc\":");
        sb.AppendLine("          list.sort((a, b) => a.name.localeCompare(b.name, \"ja\"));");
        sb.AppendLine("          break;");
        sb.AppendLine("        case \"qty_desc\":");
        sb.AppendLine("          list.sort((a, b) => b.qty - a.qty);");
        sb.AppendLine("          break;");
        sb.AppendLine("        case \"created_desc\":");
        sb.AppendLine("        default:");
        sb.AppendLine("          list.sort((a, b) => b.createdAt.localeCompare(a.createdAt));");
        sb.AppendLine("          break;");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      return list;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function updateSortPill() {");
        sb.AppendLine("      $(\"#pillSort\").textContent = `sort: ${state.sortMode}`;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function render() {");
        sb.AppendLine("      const tbody = $(\"#tbody\");");
        sb.AppendLine("      const visible = getVisibleItems();");
        sb.AppendLine("");
        sb.AppendLine("      const lowCount = visible.filter(x => x.qty > 0 && x.qty < x.min).length;");
        sb.AppendLine("      const totalQty = visible.reduce((sum, x) => sum + x.qty, 0);");
        sb.AppendLine("      $(\"#kpiItems\").textContent = String(visible.length);");
        sb.AppendLine("      $(\"#kpiLow\").textContent = String(lowCount);");
        sb.AppendLine("      $(\"#kpiQty\").textContent = String(totalQty);");
        sb.AppendLine("");
        sb.AppendLine("      if (visible.length === 0) {");
        sb.AppendLine("        tbody.innerHTML =");
        sb.AppendLine("          \"<tr>\" +");
        sb.AppendLine("          \"  <td colspan=\\\"7\\\" class=\\\"small\\\">表示できるデータがありません（検索条件を変えてみて）</td>\" +");
        sb.AppendLine("          \"</tr>\";");
        sb.AppendLine("        return;");
        sb.AppendLine("      }");
        sb.AppendLine("");
        sb.AppendLine("      const rowsHtml = visible.map(item => {");
        sb.AppendLine("        const dot = stockLevelDot(item.qty, item.min);");
        sb.AppendLine("        const catLabel = toCategoryLabel(item.category);");
        sb.AppendLine("");
        sb.AppendLine("        const name = escapeHtml(item.name);");
        sb.AppendLine("        const memo = escapeHtml(item.memo || \"\");");
        sb.AppendLine("        const status = escapeHtml(item.status);");
        sb.AppendLine("        const price = item.price > 0 ? String(item.price) : \"-\";");
        sb.AppendLine("");
        sb.AppendLine("        return (");
        sb.AppendLine("          \"<tr data-id=\\\"\" + item.id + \"\\\">\" +");
        sb.AppendLine("          \"  <td>\" +");
        sb.AppendLine("          \"    <div style=\\\"font-weight:600;\\\">\" + name + \"</div>\" +");
        sb.AppendLine("          \"    <div class=\\\"small\\\">created: \" + escapeHtml(item.createdAt) + \"</div>\" +");
        sb.AppendLine("          \"  </td>\" +");
        sb.AppendLine("          \"  <td><span class=\\\"tag\\\"><span class=\\\"dot\\\"></span>\" + catLabel + \"</span></td>\" +");
        sb.AppendLine("          \"  <td>\" +");
        sb.AppendLine("          \"    <span class=\\\"tag\\\"><span class=\\\"dot \" + dot + \"\\\"></span>\" +");
        sb.AppendLine("          \"    \" + item.qty + \" / min \" + item.min +");
        sb.AppendLine("          \"    </span>\" +");
        sb.AppendLine("          \"  </td>\" +");
        sb.AppendLine("          \"  <td><span class=\\\"tag\\\">\" + status + \"</span></td>\" +");
        sb.AppendLine("          \"  <td><span class=\\\"tag\\\">\" + escapeHtml(price) + \"</span></td>\" +");
        sb.AppendLine("          \"  <td class=\\\"small\\\">\" + memo + \"</td>\" +");
        sb.AppendLine("          \"  <td>\" +");
        sb.AppendLine("          \"    <div style=\\\"display:flex;gap:8px;flex-wrap:wrap;\\\">\" +");
        sb.AppendLine("          \"      <button type=\\\"button\\\" class=\\\"btnArchive\\\">Archive</button>\" +");
        sb.AppendLine("          \"      <button type=\\\"button\\\" class=\\\"btnDelete danger\\\">Delete</button>\" +");
        sb.AppendLine("          \"    </div>\" +");
        sb.AppendLine("          \"  </td>\" +");
        sb.AppendLine("          \"</tr>\"");
        sb.AppendLine("        );");
        sb.AppendLine("      }).join(\"\");");
        sb.AppendLine("");
        sb.AppendLine("      tbody.innerHTML = rowsHtml;");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function addItem(formData) {");
        sb.AppendLine("      const errors = validate(formData);");
        sb.AppendLine("      setErrors(errors);");
        sb.AppendLine("      if (Object.keys(errors).length > 0) return;");
        sb.AppendLine("");
        sb.AppendLine("      const item = {");
        sb.AppendLine("        id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now()),");
        sb.AppendLine("        name: formData.name.trim(),");
        sb.AppendLine("        qty: safeParseInt(formData.qty, 0),");
        sb.AppendLine("        category: formData.category,");
        sb.AppendLine("        price: safeParseFloat(formData.price, 0),");
        sb.AppendLine("        min: Math.max(0, safeParseInt(formData.min, 0)),");
        sb.AppendLine("        status: formData.status || \"active\",");
        sb.AppendLine("        memo: (formData.memo || \"\").trim(),");
        sb.AppendLine("        createdAt: nowIso(),");
        sb.AppendLine("      };");
        sb.AppendLine("");
        sb.AppendLine("      state.items.unshift(item);");
        sb.AppendLine("      saveItems(state.items);");
        sb.AppendLine("      setOk(\"追加した！\");");
        sb.AppendLine("      render();");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function deleteItem(id) {");
        sb.AppendLine("      state.items = state.items.filter(x => x.id !== id);");
        sb.AppendLine("      saveItems(state.items);");
        sb.AppendLine("      render();");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function archiveItem(id) {");
        sb.AppendLine("      const target = state.items.find(x => x.id === id);");
        sb.AppendLine("      if (!target) return;");
        sb.AppendLine("");
        sb.AppendLine("      if (target.status === \"archived\") target.status = \"active\";");
        sb.AppendLine("      else target.status = \"archived\";");
        sb.AppendLine("");
        sb.AppendLine("      saveItems(state.items);");
        sb.AppendLine("      render();");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function openModal(text) {");
        sb.AppendLine("      $(\"#exportBox\").textContent = text || \"{}\";");
        sb.AppendLine("      $(\"#modalBack\").style.display = \"flex\";");
        sb.AppendLine("      $(\"#modalBack\").setAttribute(\"aria-hidden\", \"false\");");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function closeModal() {");
        sb.AppendLine("      $(\"#modalBack\").style.display = \"none\";");
        sb.AppendLine("      $(\"#modalBack\").setAttribute(\"aria-hidden\", \"true\");");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function seed() {");
        sb.AppendLine("      const samples = [");
        sb.AppendLine("        { name: \"USB-C Cable 1m\", qty: 3, category: \"cable\", price: 780, min: 2, status: \"active\", memo: \"黒 / 急速充電対応\" },");
        sb.AppendLine("        { name: \"HDMI Adapter\", qty: 1, category: \"adapter\", price: 1900, min: 2, status: \"hold\", memo: \"相性注意\" },");
        sb.AppendLine("        { name: \"Precision Driver Set\", qty: 0, category: \"tool\", price: 2400, min: 1, status: \"active\", memo: \"発注予定\" },");
        sb.AppendLine("        { name: \"Label Sticker\", qty: 12, category: \"other\", price: 500, min: 5, status: \"active\", memo: \"棚整理用\" },");
        sb.AppendLine("      ];");
        sb.AppendLine("");
        sb.AppendLine("      const createdAt = nowIso();");
        sb.AppendLine("      const list = samples.map((s, i) => ({");
        sb.AppendLine("        id: crypto.randomUUID ? crypto.randomUUID() : String(Date.now() + i),");
        sb.AppendLine("        createdAt,");
        sb.AppendLine("        ...s,");
        sb.AppendLine("      }));");
        sb.AppendLine("");
        sb.AppendLine("      state.items = list.concat(state.items);");
        sb.AppendLine("      saveItems(state.items);");
        sb.AppendLine("      render();");
        sb.AppendLine("      setOk(\"サンプル投入OK\");");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function readForm() {");
        sb.AppendLine("      return {");
        sb.AppendLine("        name: $(\"#name\").value,");
        sb.AppendLine("        qty: $(\"#qty\").value,");
        sb.AppendLine("        category: $(\"#category\").value,");
        sb.AppendLine("        price: $(\"#price\").value,");
        sb.AppendLine("        min: $(\"#min\").value,");
        sb.AppendLine("        status: $(\"#status\").value,");
        sb.AppendLine("        memo: $(\"#memo\").value,");
        sb.AppendLine("      };");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function resetForm() {");
        sb.AppendLine("      $(\"#name\").value = \"\";");
        sb.AppendLine("      $(\"#qty\").value = \"\";");
        sb.AppendLine("      $(\"#category\").value = \"\";");
        sb.AppendLine("      $(\"#price\").value = \"\";");
        sb.AppendLine("      $(\"#min\").value = \"\";");
        sb.AppendLine("      $(\"#status\").value = \"active\";");
        sb.AppendLine("      $(\"#memo\").value = \"\";");
        sb.AppendLine("      setErrors({});");
        sb.AppendLine("      setOk(\"\");");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function clearAll() {");
        sb.AppendLine("      const ok = confirm(\"全データを削除します。よろしいですか？\");");
        sb.AppendLine("      if (!ok) return;");
        sb.AppendLine("");
        sb.AppendLine("      state.items = [];");
        sb.AppendLine("      saveItems(state.items);");
        sb.AppendLine("      render();");
        sb.AppendLine("      setOk(\"全削除しました\");");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function toggleSort() {");
        sb.AppendLine("      const modes = [\"created_desc\", \"created_asc\", \"name_asc\", \"qty_desc\"];");
        sb.AppendLine("      const idx = modes.indexOf(state.sortMode);");
        sb.AppendLine("      const next = modes[(idx + 1) % modes.length];");
        sb.AppendLine("      state.sortMode = next;");
        sb.AppendLine("      updateSortPill();");
        sb.AppendLine("      render();");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function exportVisible() {");
        sb.AppendLine("      const visible = getVisibleItems();");
        sb.AppendLine("      const text = JSON.stringify(visible, null, 2);");
        sb.AppendLine("      openModal(text);");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    function init() {");
        sb.AppendLine("      state.items = loadItems();");
        sb.AppendLine("      updateSortPill();");
        sb.AppendLine("      render();");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#form\").addEventListener(\"submit\", (e) => {");
        sb.AppendLine("        e.preventDefault();");
        sb.AppendLine("        addItem(readForm());");
        sb.AppendLine("      });");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#btnReset\").addEventListener(\"click\", () => resetForm());");
        sb.AppendLine("      $(\"#btnClearAll\").addEventListener(\"click\", () => clearAll());");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#search\").addEventListener(\"input\", (e) => {");
        sb.AppendLine("        state.search = e.target.value;");
        sb.AppendLine("        render();");
        sb.AppendLine("      });");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#filterStatus\").addEventListener(\"change\", (e) => {");
        sb.AppendLine("        state.filterStatus = e.target.value;");
        sb.AppendLine("        render();");
        sb.AppendLine("      });");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#tbody\").addEventListener(\"click\", (e) => {");
        sb.AppendLine("        const btn = e.target.closest(\"button\");");
        sb.AppendLine("        if (!btn) return;");
        sb.AppendLine("");
        sb.AppendLine("        const tr = e.target.closest(\"tr\");");
        sb.AppendLine("        if (!tr) return;");
        sb.AppendLine("");
        sb.AppendLine("        const id = tr.getAttribute(\"data-id\");");
        sb.AppendLine("        if (!id) return;");
        sb.AppendLine("");
        sb.AppendLine("        if (btn.classList.contains(\"btnDelete\")) {");
        sb.AppendLine("          deleteItem(id);");
        sb.AppendLine("          return;");
        sb.AppendLine("        }");
        sb.AppendLine("");
        sb.AppendLine("        if (btn.classList.contains(\"btnArchive\")) {");
        sb.AppendLine("          archiveItem(id);");
        sb.AppendLine("          return;");
        sb.AppendLine("        }");
        sb.AppendLine("      });");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#btnSort\").addEventListener(\"click\", () => toggleSort());");
        sb.AppendLine("      $(\"#btnExport\").addEventListener(\"click\", () => exportVisible());");
        sb.AppendLine("      $(\"#btnSeed\").addEventListener(\"click\", () => seed());");
        sb.AppendLine("");
        sb.AppendLine("      $(\"#btnOpenHelp\").addEventListener(\"click\", () => openModal(\"{\\n  \\\"help\\\": true\\n}\"));");
        sb.AppendLine("      $(\"#btnCloseModal\").addEventListener(\"click\", () => closeModal());");
        sb.AppendLine("      $(\"#modalBack\").addEventListener(\"click\", (e) => {");
        sb.AppendLine("        if (e.target.id === \"modalBack\") closeModal();");
        sb.AppendLine("      });");
        sb.AppendLine("");
        sb.AppendLine("      window.addEventListener(\"keydown\", (e) => {");
        sb.AppendLine("        if (e.key === \"Escape\") closeModal();");
        sb.AppendLine("      });");
        sb.AppendLine("    }");
        sb.AppendLine("");
        sb.AppendLine("    init();");

        sb.AppendLine("  </script>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");

        return sb.ToString();
    }
}

